// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/yi-nology/git-sync-service/biz/router"
)

// customizeRegister registers customize routers.
// 实现放在 biz/router.CustomizedRegister，公网/内网壳共用。
func customizedRegister(r *server.Hertz) {
	router.CustomizedRegister(r)
}
