// Code generated by hertz generator.

package git_sync

import (
	"context"
	"runtime"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	system "github.com/yi-nology/git-ferry/biz/model/system"
	"github.com/yi-nology/git-ferry/internal/converter"
	"github.com/yi-nology/git-ferry/internal/pkg/response"
	"github.com/yi-nology/git-ferry/internal/pkg/safe"
	"github.com/yi-nology/git-ferry/internal/version"
)

// SystemStatus 返回系统状态信息（管理面板用）。
func SystemStatus(ctx context.Context, c *app.RequestContext) {
	svc, ok := requireSyncService(c)
	if !ok {
		return
	}

	// CountRepos 与 CountTasksByStatus 互不依赖,并行执行。
	// 注:CountRepos/CountTasksByStatus 不接受 ctx(core API 限制),
	// goroutine 无法被取消,但都是快速 count 查询,泄漏风险可忽略
	type repoCountResult struct {
		count int64
		err   error
	}
	type taskCountResult struct {
		counts map[string]int64
		err    error
	}
	repoCh := make(chan repoCountResult, 1)
	taskCh := make(chan taskCountResult, 1)
	safe.Go("CountRepos", func() {
		var r repoCountResult
		// defer LIFO:先注册发送、后注册 recover,panic 时 recover 先写 err 再发送
		defer func() { repoCh <- r }()
		defer safe.RecoverToErr("CountRepos", &r.err)
		r.count, r.err = svc.CountRepos()
	})
	safe.Go("CountTasksByStatus", func() {
		var r taskCountResult
		defer func() { taskCh <- r }()
		defer safe.RecoverToErr("CountTasksByStatus", &r.err)
		r.counts, r.err = svc.CountTasksByStatus()
	})

	rr := <-repoCh
	if rr.err != nil {
		response.InternalError(c, "get repo count failed")
		return
	}
	tr := <-taskCh
	if tr.err != nil {
		response.InternalError(c, "get task count failed")
		return
	}
	repoCount := rr.count
	taskCounts := tr.counts
	taskTotal := taskCounts["total"]
	runningCount := taskCounts["running"]
	failedCount := taskCounts["failed"]

	response.Success(c, &system.SystemStatusData{
		Status:      "running",
		Version:     version.Version,
		Uptime:      int64(time.Since(startTime).Seconds()),
		RepoCount:   converter.SafeInt64ToInt32(repoCount),
		TaskCount:   converter.SafeInt64ToInt32(taskTotal),
		RunningTask: converter.SafeInt64ToInt32(runningCount),
		FailedTask:  converter.SafeInt64ToInt32(failedCount),
		GoVersion:   runtime.Version(),
		Platform:    runtime.GOOS + "/" + runtime.GOARCH,
	})
}
